---
version: '3.8'
services:
  movies:
    image: subbu8docker/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
   train:
    image: subbu8docker/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
   dth:
    image: subbu8docker/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
   recharge:
    image: subbu8docker/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
